AWSTemplateFormatVersion: "2010-09-09"

Description: Creates the application load balancer

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Network Configuration"
        Parameters:
          - VpcID
          - PublicSubnet1
          - PublicSubnet2
          - SecurityGroupALB
      - Label:
          default: "Certificate Configuration"
        Parameters:
          - ACMCertificateArn
     
Parameters:
  VpcID:
    Description: The name of the VPC stack
    Type: String

  ACMCertificateArn:
    Description: The ARN of the ACM certificate
    Type: String
    Default: arn:aws:acm:us-east-1:426361357193:certificate/9ee554b5-ea36-472e-a0d5-b19caf420c41
  
  PublicSubnet1:
    Description: Import Public subnet 1
    Type: String

  PublicSubnet2:
    Description: Import Public subnet 2
    Type: String
  
  SecurityGroupALB:
    Description: Import ALB Security group
    Type: String

Resources:
  # Application Load Balancer
  PracticalALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
      Name: PracticalALB
      Scheme: internet-facing 
      SecurityGroups:
        - !Ref SecurityGroupALB
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Tags:
        - Key: Name
          Value: PracticalALB
      Type: application

  # Application Load Balancer Listener - port 80
  PracticalALBListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: "443"
            StatusCode: HTTP_301
      LoadBalancerArn: !Ref PracticalALB
      Port: 80
      Protocol: HTTP

  # Application Load Balancer Listener - port 443
  PracticalALBListenerCert:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      Certificates:
        - CertificateArn: !Ref ACMCertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref PracticalTargetGroup
      LoadBalancerArn: !Ref PracticalALB
      Port: 443
      Protocol: HTTPS

  # Target Group for the Application Load Balancer
  PracticalTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200
      Name: PracticalTargetGroup
      Port: 80
      Protocol: HTTP
      TargetType: instance
      Tags:
        - Key: Name
          Value: PracticalTargetGroup
      VpcId: !Ref VpcID

Outputs:
  # Export Load Balancer Target Group
  ALBTargetGroup:
    Description: Web Server target group
    Value: 
      Ref: PracticalTargetGroup

  # Export Application Load balancer DNS
  ALBDNS:
    Description: DNS of the application load balancer
    Value: !GetAtt PracticalALB.DNSName

  # Export Application Load balancer Zone ID
  ALBZoneID:
    Description: Zone ID of the application load balancer
    Value: !GetAtt PracticalALB.CanonicalHostedZoneID