version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing AWS CLI..."
      - pip install awscli --upgrade

  pre_build:
    commands:
      - echo "Listing files in the working directory..."
      - ls -al
      - echo "Navigating to project directory"
      - cd projectfolder
      - echo "Verifying files inside the project directory"
      - ls -al

  build:
    commands:
      - echo "Validating CloudFormation templates..."
      - for template in master.yaml vpc.yaml natgateway.yaml alb.yaml asg.yaml route53.yaml; do
          aws cloudformation validate-template --template-body file://$template || { echo "Validation failed for $template" && exit 1; }
        done

      - echo "Deploying CloudFormation stack..."
      - aws cloudformation deploy --template-file master.yaml --stack-name codebuilddemoproject --capabilities CAPABILITY_NAMED_IAM

      - echo "Retrieving Route 53 output from the nested stack..."
      - ROUTE53_STACK_NAME=$(aws cloudformation describe-stack-resources --stack-name codebuilddemoproject --query "StackResources[?LogicalResourceId=='ROUTE53Stack'].PhysicalResourceId" --output text)
      - DOMAIN_NAME=$(aws cloudformation describe-stacks --stack-name $ROUTE53_STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='WebsiteURL'].OutputValue" --output text)
      - echo "Website is available at - $DOMAIN_NAME"

artifacts:
  files:
    - master.yaml
    - vpc.yaml
    - natgateway.yaml
    - alb.yaml
    - asg.yaml
    - route53.yaml